---
title: "R Notebook"
output: html_notebook
---

```{r}
library(rio)

autoridades= import("https://github.com/PULSO-PUCP/ERM_2022/raw/main/competitividad/ERM2018_Autoridades_Provincial.xlsx")
```
```{r}
aut.max = aggregate(`% Votos organización política` ~ Región + Provincia, data= autoridades, max)
aut.max2 = aggregate(`% Votos organización política` ~ Región + Provincia, data= autoridades, function(x) sort(x)[2])

library(tidyverse)

dif = merge(aut.max, aut.max2, by= c("Región", "Provincia"))

dif$competitividad = dif$`% Votos organización política.x` - dif$`% Votos organización política.y`

colnames(dif)[c(1,2)] = c("DEPARTAMEN","PROVINCIA")
```

```{r}
library(sf)
library(ggplot2)
library(ggpubr)

mapaP = st_read("C:/Users/soyma/Documents/GitHub/ERM_2022/PROVINCIAS.shp") #cambiar según directorio

dif[dif$PROVINCIA=="ANTONIO RAIMONDI","PROVINCIA"]= "ANTONIO RAYMONDI"

mapaprov = merge(mapaP, dif, by=c("DEPARTAMEN","PROVINCIA"), all=TRUE)

mapaprov$puntos= mapaprov$competitividad*100 
```

```{r}
base1 = ggplot(data = mapaprov) + theme_light()
```

```{r}
mapaprov$Categorias = cut(mapaprov$puntos, breaks = 5)
```

```{r}
summary(mapaprov$Categorias)
```

```{r}
library(viridis)
mapaCompetitividad = base1 +
  geom_sf(aes(fill= cut(puntos, breaks = 5)), size = 0.005) + 
  labs(fill = "Puntos porcentuales")+ 
  scale_fill_viridis(discrete = TRUE, option= "rocket", direction = -1)# +
#  ggtitle("Avance de la vacunación a nivel provincial")


mapaCompetitividad
```

```{r}
ggsave("mapaCompetitividad.png")
```

