---
title: "Limpieza y preprocesamiento"
output: html_notebook
---

```{r}
### Carga de bases:

#### 1. Personas vacunadas

library(readr)
library(archive)
tf <- tempfile() ; td <- tempdir()
file.path <- "https://cloud.minsa.gob.pe/s/oHF5JSLEk8KzpPW/download"
download.file( file.path , tf , mode = "wb" )
vacunas_covid <- read.csv(archive_read(tf, "TB_VACUNACION_COVID19.csv"))
```

```{r}
#### 2. Ubigeos 

ubigeos <- read_csv("https://cloud.minsa.gob.pe/s/GkfcJD8xKHJeCqn/download")
```

```{r}
#### 3. Padrón de población

tf2 <- tempfile() ; td <- tempdir()
file.path2 <- "https://cloud.minsa.gob.pe/s/6J5obcebX6c8rQ8/download"
download.file( file.path2 , tf2 , mode = "wb" )
TB_PERSONA <- read.csv(archive_read(tf2, "TB_PERSONA.csv"))
```


```{r}
### Limpieza de bases

#### 1. Padrón de población
#a. Consignar año de nacimiento como número
#b. Filtrar a los nacidos antes de 2004
#c. Mantener a los fallecidos
#d. Agregar los datos por ubigeo de domicilio

names(TB_PERSONA)[names(TB_PERSONA) == 'ï..id_persona'] <- 'id_persona'

names(vacunas_covid)[names(vacunas_covid) == 'ï..id_persona'] <- 'id_persona'

TB_PERSONA$anho_nac = as.numeric(TB_PERSONA$anho_nac)

Poblacion=subset(TB_PERSONA,anho_nac<2003)

Poblacion[Poblacion=='NA'] <- NA

Poblacion$fecha_fallecido <- as.Date(Poblacion$fecha_fallecido,format= "%d/%m/%Y")

Poblacion <- Poblacion[is.na(Poblacion$fecha_fallecido),]

library(dplyr)

PoblacionD18=aggregate(id_persona~id_ubigeo_domicilio,data=Poblacion,FUN=length)
```

```{r}
#### 2. Personas vacunadas
#a. Mantener solo segundas dosis (pauta completa)
#b. Filtrar a los compeltamente vacunados antes del 31 de diciembre. Combinar con población de 18 años a más. Agregar por ubigeo de domicilio.
#c. Juntar las tres bases de las tres fechas con la base de población de 18 años a más.

library(lubridate)

Vacuna=subset(vacunas_covid,dosis==2 | dosis==3)

VacunaCompleta = Vacuna[!duplicated(Vacuna$id_persona),]

VacunaCompleta$fecha_vacunacion1 <- ymd(VacunaCompleta$fecha_vacunacion)

#Vacuna31Dic=subset(Vacuna, fecha_vacunacion1< "2021-12-31")

PoblacionVacunada=merge(VacunaCompleta,Poblacion,by="id_persona")

#rm(TB_PERSONA) 

PoblacionVac=aggregate(id_persona~id_ubigeo_domicilio,data=PoblacionVacunada,FUN=length)

names(PoblacionVac)[names(PoblacionVac) == 'id_persona'] <- 'Nro'

PoblacionD18=merge(PoblacionVac, PoblacionD18)

BaseDistrital=merge(PoblacionD18,ubigeos,by.x="id_ubigeo_domicilio",by.y="id_ubigeo")

names(BaseDistrital)[names(BaseDistrital) == 'id_persona'] <- 'Poblacion18'

#BaseProv=aggregate(cbind("Nro", "Poblacion18")~ departamento_inei + departamento +
 #                    provincia_inei+provincia+macroregion_inei+macroregion_minsa,
  #                 data=BaseDistrital,FUN=length)

BaseProv <- BaseDistrital %>% 
  group_by(departamento_inei, departamento, provincia_inei, provincia) %>%
  summarise_at(vars(Nro, Poblacion18), sum)

BaseProv$Avance=BaseProv$Nro/BaseProv$Poblacion18*100
```

```{r}
write.csv(BaseDistrital2,"BaseDistrital.csv")
```
